#:schema node_modules/wrangler/config-schema.json
name = "files-pydantic-run"
main = "src/index.ts"
routes = ["files.pydantic.run/*"]
workers_dev = false
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = true
